# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: New Things
email: cjayscue@live.unc.edu
description: New Places
baseurl: "" # the subpath of your site, e.g. /blog
url: /
twitter_username: 
github_username:  cjayscue

# Build settings
markdown: kramdown
